# Generated by Django 4.2.16 on 2024-12-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacherprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='static/teacher_profiles/'),
        ),
    ]
