# Generated by Django 4.2.16 on 2024-12-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacherprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='class_teach',
            field=models.JSONField(default=list, null=True),
        ),
    ]
