# Generated by Django 4.2.16 on 2024-12-12 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_class_class_name_alter_subject_name'),
        ('teacher', '0004_alter_teacherprofile_class_teach'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.class'),
        ),
    ]
