# Generated by Django 4.2.16 on 2024-12-27 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacherprofile_class_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='phone_number',
        ),
    ]
