# Generated by Django 4.2.16 on 2024-12-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_teacherprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='phone_number',
        ),
    ]
