# Generated by Django 4.2.16 on 2024-10-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
