# Generated by Django 4.2.16 on 2024-12-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_class_class_name_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_subject',
            field=models.JSONField(default=list, null=True),
        ),
    ]
