# Generated by Django 4.2.16 on 2025-01-02 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_managers_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 2, 9, 32, 49, 15166, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
