# Generated by Django 4.2.16 on 2025-01-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
    ]
