# Generated by Django 4.2.16 on 2024-10-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='grade',
            new_name='gender',
        ),
    ]
