# Generated by Django 4.2.16 on 2024-12-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_grade_studentprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='student_profiles/'),
        ),
    ]
