# Generated by Django 4.2.16 on 2024-12-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='static/student_profiles/'),
        ),
    ]
